projects:
  userwizardanswers:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: dy46pwtvgvdvfl7nv57uyvns5i
      endpoints:
        prod: >-
          https://regdxod7k5esvkkuhiquif7cgq.appsync-api.us-east-1.amazonaws.com/graphql
